# Generated by Django 3.0.5 on 2020-04-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liner_note', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.IntegerField()),
                ('line', models.IntegerField()),
                ('slug', models.SlugField(max_length=100)),
                ('text', models.TextField(max_length=300)),
                ('varies_from_gabler', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='linernote',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='line',
            name='liner_notes',
            field=models.ManyToManyField(to='liner_note.LinerNote'),
        ),
        migrations.AlterUniqueTogether(
            name='line',
            unique_together={('episode', 'line')},
        ),
    ]
