# Generated by Django 3.0.5 on 2020-04-20 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liner_note', '0002_auto_20200419_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='text',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='varies_from_gabler',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
