# Generated by Django 3.0.5 on 2020-04-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liner_note', '0003_auto_20200419_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linernote',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
